### ISSUE TITLE
Set locale list for Fenix to get going

### ISSUE THREAD

**Issue by Pike** [mozilla-l10n/android-l10n#17]
Right now, we don't have an explicit locale list for Fenix.

By incidence, it's using what we have on android-components, and that's also exposed on pontoon right now:

```toml
locales = [
  "de",
  "es",
  "fr",
  "it",
  "ja",
  "ko",
  "zh-CN",
  "zh-TW",
]
```

We have strings in git for de, fr, it, zh-CN, zh-TW. I know that there are suggestions for at least `es`. As of now, not for Korean yet.

Least surprises for people would be to just add this exact list for now, and then expand soon after?

CC @Delphine

**Comment by Delphine** [comment]
For beta, we'd just need to add "es-ES" to that, since it's on the mobile wishlist. We can start with the list you've called out, and add "es-ES" some time next week. 

I'm wondering if we should just wait post-Beta at this point for expanding to more locales. I'm thinking we can add all Fennec locales at one point. Not sure we wanna do that all in one go, or do that in smaller batches. Thoughts?

**Comment by flodolo** [comment]
> I'm thinking we can add all Fennec locales at one point.

I wouldn't do that, at least not without heavy filtering based on how active they are on Pontoon. There are unowned locales in there (e.g. af, ga-IE), it doesn't make sense to add them.

**Comment by Delphine** [comment]
Oh yeah, definitely. Didn't mention it here, but I need to do some filtering of course. No point in adding stale locales
